<div class="widgets">
    <div class="oneTwo">
         <img src="<?php echo $this->baseUrl(); ?>/img/formation1.jpg" alt="This Guy" />
    </div>
    <div class="oneTwo">
        <div class="widget">
            <div class="title">
                <img class="titleIcon" alt="" src="<?php echo $this->baseUrl();?>/images/icons/dark/bag.png">
                <h6>Authentication</h6>
            </div>
            <div class="body textC">
               <?php echo $this->form; ?>
            </div>
        </div>
    </div >
</div >