<div class='row-fluid landing'>
        <div class="span5 profilePerson">
			<img src="/img/formation1.jpg" alt="This Guy"/>
			<div class='profileOptions'>
			</div>
        </div>
        <div class='span4'><br/></div>
        <div class='span4 borBox'>
                <div class='navbar blue'>
                        <div class='navbar-inner'>
                                <div class='container-fluid'>
                                        <p class='wtext'>Authentification</p>
                                </div>
                        </div>	
                </div>
                <div class='row-fluid well borBox whiter'>
                        <div class='form-horizontal tCenter'>
                           <?php
                                $this->title = "Ajouter un nouvel album";
                                $this->headTitle($this->title);
                                echo $this->form;
                            ?>

                        </div>	
                </div>
        </div> 

</div>	