<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8">
            <?php echo $this->headTitle($this->translate('Gestion Formation'))->setSeparator(' - ')->setAutoEscape(false) ?>

            <?php
            echo $this->headMeta()
                    ->appendName('viewport', 'width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;')
                    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ?>

            <!-- Le styles -->
            <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/img/favicon.ico'))
                    ->prependStylesheet($this->baseUrl() . '/css/main.css');
             echo $this->jQuery()
			            ->setVersion('1.7.1')
			            ->setUiVersion('1.8.11')
			            ->enable()
            			->uiEnable();
            ?>

            <!-- Scripts -->
            

            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/spinner/ui.spinner.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/spinner/jquery.mousewheel.js"></script>

            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/charts/excanvas.min.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/charts/jquery.sparkline.min.js"></script>

            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/uniform.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/jquery.cleditor.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/jquery.validationEngine-en.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/jquery.validationEngine.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/jquery.tagsinput.min.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/autogrowtextarea.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/jquery.maskedinput.min.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/jquery.dualListBox.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/jquery.inputlimiter.min.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/forms/chosen.jquery.min.js"></script>

            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/wizard/jquery.form.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/wizard/jquery.validate.min.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/wizard/jquery.form.wizard.js"></script>

            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/uploader/plupload.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/uploader/plupload.html5.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/uploader/plupload.html4.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/uploader/jquery.plupload.queue.js"></script>

            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/tables/datatable.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/tables/tablesort.min.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/tables/resizable.min.js"></script>

            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/ui/jquery.tipsy.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/ui/jquery.collapsible.min.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/ui/jquery.prettyPhoto.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/ui/jquery.progress.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/ui/jquery.timeentry.min.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/ui/jquery.colorpicker.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/ui/jquery.jgrowl.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/ui/jquery.breadcrumbs.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/ui/jquery.sourcerer.js"></script>

            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/calendar.min.js"></script>
            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/elfinder.min.js"></script>

            <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/custom.js"></script>

    </head>
    <body <?php if ($this->page === 'notfound') {echo "class='nobg errorPage'"; } ?>>
	<?php if ($this->page === 'notfound') { ?>
            <div class="topNav"></div>    
            <!-- Main content wrapper -->
            <div class="errorWrapper">
                <span class="sadEmo"></span>
                <span class="errorTitle">Ahh, quelque chose a mal tourné :(</span>
                <span class="errorNum">404</span>
                <span class="errorDesc">Oops! Désolé, une erreur s'est produite. Page non trouvée!</span>
                <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>" title="" class="button dredB"><span>Rtour</span></a>
            </div>
        <?php } elseif ($this->page === 'popup') { ?>
            <div class="wrapper">
    <?php echo $this->layout()->content; ?>
            </div>
<?php } else { ?>
            <!--<div id="leftSide">
               <div class="logo"><a href="#"><img src="<?php echo $this->baseUrl(); ?>/img/logo.png" alt="" /></a></div>
                <div class="sidebarSep mt0"></div>
                
                <form action="" class="sidebarSearch">
                    <input type="text" name="search" placeholder="search..." id="ac" />
                    <input type="submit" value="" />
                </form>
                <div class="sidebarSep"></div>
            </div>-->
            <!-- Right side -->
            <div id="rightSide">
                <!-- Top fixed navigation -->
                <div class="topNav">
    <?php if (isset($this->sessiondata)) { ?>
                        <div class="wrapper">
                            <div class="userNav">
                                <ul>
                                    <li><a href="#" title=""><img src="<?php echo $this->baseUrl(); ?>/images/userPic.png" alt="" /></a><span><?php echo $this->sessiondata['firstName'] . " " . $this->sessiondata['lastName'] ?></span></li>
                                    <li><a href="<?php echo $this->url(array('controller' => 'index',
            'action' => 'logout'));
        ?>" title=""><img src="<?php echo $this->baseUrl(); ?>/images/icons/topnav/logout.png" alt="" /><span>Déconnecter</span></a></li>
                                </ul>
                            </div>
                            <div class="clear"></div>
                        </div>
    <?php } ?>
                </div>

                <!-- Title area -->
                <div class="titleArea">
                    <div class="wrapper">
                        <div class="pageTitle">
                            <h5>GESTION FORMATION</h5>
                            <span>Outil de suivi de formation.</span>
                        </div>
                                       <?php if (isset($this->sessiondata) && ($this->sessiondata['cp'] == 1 || $this->sessiondata['admin'] == 1)) { ?>
                            <div class="controlB">
                                <ul>
                                    <li <?php if ($this->page === 'adminIndex') {
                                       echo "id = 'active'";
                                   } ?>>
                                        <a href="<?php echo $this->url(array('controller' => 'index',
                                       'action' => 'admin'));
                                   ?>" title=""><img src="<?php echo $this->baseUrl(); ?>/images/icons/control/32/home.png" alt="" /><span>Accueil</span></a></li>
                                    <li <?php if ($this->page === 'formation') {
                                       echo "id = 'active'";
                                   } ?> >
                                        <a href="<?php echo $this->url(array('controller' => 'formation',
                                       'action' => 'index'));
                                   ?>" title=""><img src="<?php echo $this->baseUrl(); ?>/images/icons/control/32/document-library.png" alt="" /><span>Formations</span></a></li>
                                    <li <?php if ($this->page === 'assign') {
                                       echo "id = 'active'";
                                   } ?>>
                                        <a href="<?php echo $this->url(array('controller' => 'formation',
                                       'action' => 'assign'));
                                   ?>" title=""><img src="<?php echo $this->baseUrl(); ?>/images/icons/control/32/milestone.png" alt="" /><span>Affectation</span></a></li>
                                </ul>
                                <div class="clear"></div>
                            </div>
            <?php } ?>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="line"></div>
                <div class="wrapper">
    <?php echo $this->layout()->content; ?>
                </div>
                <!-- Footer line -->
                <div id="footer">
                    <div class="wrapper">Copyright &copy;2014 Astek Mauritius all rights reserved. </div>
                </div>
    <?php echo $this->inlineScript() ?>
            </div>
<?php } ?>
    </body>
     
</html>

