<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/img/favicon.ico'))
                        ->prependStylesheet($this->baseUrl() . '/css/style-user.css')
                        ->prependStylesheet($this->baseUrl() . '/css/jquery.dataTables.css')
						->prependStylesheet($this->baseUrl() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->baseUrl() . '/css/glyphicons.css')
       					?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            
			->prependFile($this->baseUrl() . '/js/bootstrap.min.js')
            ->prependFile($this->baseUrl() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->baseUrl() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
             ->prependFile($this->baseUrl() . '/js/jquery.dataTables.js')
             ->prependFile($this->baseUrl() . '/js/jquery.min.js')
            
        ; ?>
    </head>
    <body>
	
<!-- start header -->
<div class="header_bg">
<div class="wrap">
	<div class="header">
		<div class="logo">
			<!--<a href="index.html"><img src="images/logo.png" alt=""/> </a>-->
			<ul class="icon1 sub-icon1">
				<li><a class="active-icon c1" href="#"><i>Formation</i></a>
			</ul>
		</div>
            <a class="deconnet" href="<?php echo $this->url(array('controller'=>'index',
'action'=>'logout'));?>" title=""><img src="<?php echo $this->baseUrl();?>/images/icons/topnav/logout.png" alt="" /><span>Déconnecter</span></a>
		<?php 
		if(Zend_Controller_Front::getInstance()->getRequest()->getActionName()=="index"){?>
		<div class="h_icon">
			<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
 				<span class="glyphicon glyphicon-star"></span> Demander une nouvelle formation
			</button>
		</div>
		<?php }?>
		<div class="clear"></div>

	</div>
	
</div>
</div>
<div class="header_btm">
	<div class="wrap">
		<div class="header_sub">
			<div class="h_menu">
				<ul>
					<li class="active"><a href="index.html">Formation</a></li> 
				</ul>
			</div>	  
		<div class="clear"></div>
	</div>
</div>
</div>

<!-- start slider -->
			<div id="da-slider" class="da-slider">
			<br>
			<?php echo $this->layout()->content ?>
				
</div>	

        <?php echo $this->inlineScript(); ?>
    </body>
</html>
