<?php 
        $this->title = "Ajouter une nouvelle formation";
        $this->headTitle($this->title); ?>
        
<div class="widget">
    <div class="title">
        <img class="titleIcon" alt="" src="<?php echo $this->baseUrl();?>/images/icons/dark/add.png">
        <h6>Ajouter une nouvelle formation</h6>
    </div>  
    <div class="body textL form">  
       <?php echo $this->form;  ?>
   </div>
</div>   