<div class="modal fade" id="al" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
     
        <h4 class="modal-title titre" id="myModalLabel">Liste des notes </h4>
      </div>
      <br>
			   <table id="table-note" class="display" cellspacing="0" width="100%">
							<thead>
								<tr>
									<th id="df">Date</th>
									<th>Note</th>
								</tr>
							</thead>
							<tbody>
                                                            <tr><td></td><td id="load"></td></tr>
							</tbody>
			</table>
<br>
</div>
<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
</div>
</div>
