<div class="modal fade" id="al" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title titre" id="myModalLabel">Demander une nouvelle formation</h4>
      </div>
      <br>
			<table id="table-note" class="display" cellspacing="0" width="100%">
							<thead>
								<tr>
									<th>Date</th>
									<th>Note</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>10/12/2014</td>
									<td>70</td>
								</tr>
								<tr>
									<td>10/12/2012</td>
									<td>60</td>
								</tr>
								<tr>
									<td>10/12/2012</td>
									<td>60</td>
								</tr>
								<tr>
									<td>10/12/2012</td>
									<td>60</td>
								</tr>
								<tr>
									<td>10/12/2012</td>
									<td>60</td>
								</tr>
								<tr>
									<td>10/12/2012</td>
									<td>60</td>
								</tr>
							</tbody>
			</table>
<br>
</div>
<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
</div>
</div>
 <?php print_r($this->notes);?>