
<div id="chron1" class="chrono">09:98:087  </div>
<div class="contrat" id="contrat">
    <p>
        Avec ce QCM  vous pouvez tester votre connaissance du framework Symfony 2 de façon approfondie, aussi bien en domaine qu’en niveau (questions débutant à expert).
    </p>
    <br>
    <p>
        Les domaines principaux explorés sont :
    </p>
    <br>
    <ul>
        <li>
            <img src="/images/rightArrow.png"> La connaissance de ORM et le fonctionnement avec Doctrine
        </li>
        <li>
            <img src="/images/rightArrow.png"> La connaissance des annotations,
        </li>
        <li>
            <img src="/images/rightArrow.png"> L’authentification et les questions de sécurité
        </li>
        <li>
            <img src="/images/rightArrow.png"> Le travail avec les injections de dépendance et les services
        </li>
        <li>
            <img src="/images/rightArrow.png"> La structure de Symfony
        </li>
    </ul>
    <br>
    <input type="checkbox" name="chrono" id="chrono" value=""/> Activer le chronometre <br/>
    <button type="button" id="btn_start_test" value="<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam('id');?>" class="btn btn-primary btn-contrat">Commencer le test</button>
</div>
